/**
 * NoiseModelling is a library capable of producing noise maps. It can be freely used either for research and education, as well as by experts in a professional use.
 * <p>
 * NoiseModelling is distributed under GPL 3 license. You can read a copy of this License in the file LICENCE provided with this software.
 * <p>
 * Official webpage : http://noise-planet.org/noisemodelling.html
 * Contact: contact@noise-planet.org
 */

package org.noise_planet.noisemodelling.pathfinder.path;

import org.h2gis.utilities.SpatialResultSet;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Geometry;
import org.noise_planet.noisemodelling.pathfinder.SourcePointInfo;
import org.noise_planet.noisemodelling.pathfinder.profilebuilder.CutProfile;
import org.noise_planet.noisemodelling.pathfinder.profilebuilder.ProfileBuilder;
import org.noise_planet.noisemodelling.pathfinder.utils.geometry.QueryGeometryStructure;
import org.noise_planet.noisemodelling.pathfinder.utils.geometry.QueryRTree;
import org.noise_planet.noisemodelling.pathfinder.utils.geometry.Orientation;

import java.util.*;


/**
 * Data input for a propagation process (Sub domain generated by ReceiverGridNoiseMapLoader).
 * 
 * This class manages the spatial data structure for noise propagation calculations, including:
 * - Sound sources (points, lines, polygons) with their geometries and attributes
 * - Receivers (observation points) with their coordinates
 * - Spatial indexing for efficient geometry queries
 * - Configuration for reflection, diffraction, and propagation parameters
 * - Bridge properties and source orientations for advanced modeling
 * 
 * The Scene acts as a container for all geometric and acoustic data needed to perform
 * noise propagation calculations between sources and receivers in a 3D environment.
 *
 * @author Nicolas Fortin
 * @author Pierre Aumond
 * @author Adrien Le Bellec
 */
public class Scene {
    /**
     * Enumerates how source height is interpreted.
     */
    public enum HeightType {
        /** Height value is relative to ground elevation (or bridge deck for bridge sources). */
        RELATIVE,
        /** Height value is absolute elevation in the same coordinate system as DEM. */
        ABSOLUTE;
        /**
         * Convert string representation to Position enum value.
         * Case-insensitive matching is supported.
         * 
         * @param value String representation of girder type
         * @return Corresponding GirderType enum value
         * @throws IllegalArgumentException if the value doesn't match any enum constant
         */
        public static HeightType fromString(String value) {
            if (value == null) {
                return RELATIVE; // Default value
            }
            try {
                return HeightType.valueOf(value.toUpperCase());
            } catch (IllegalArgumentException e) {
                throw new IllegalArgumentException("Unknown HeightType: " + value + 
                        ". Valid values are: RELATIVE, ABSOLUTE");
            }
        }
    }

    /** Default maximum propagation distance in meters */
    public static final double DEFAULT_MAX_PROPAGATION_DISTANCE = 1200;
    /** Default maximum reflection distance in meters */
    public static final double DEFAULT_MAXIMUM_REF_DIST = 700;
    /** Default receiver distance in meters */
    public static final double DEFAULT_RECEIVER_DIST = 1.0;
    /** Default ground absorption coefficient */
    public static final double DEFAULT_G = 0.0;
    /** Default building absorption coefficient */
    public static final double DEFAULT_G_BUILDING = 0.0;
    /** Database field name for yaw angle (rotation around vertical axis) */
    public static final String YAW_DATABASE_FIELD = "YAW";
    /** Database field name for pitch angle (rotation around horizontal axis) */
    public static final String PITCH_DATABASE_FIELD = "PITCH";
    /** Database field name for roll angle (rotation around forward axis) */
    public static final String ROLL_DATABASE_FIELD = "ROLL";
    /** Database field name for directivity identifier */
    public static final String DIRECTIVITY_DATABASE_FIELD = "DIR_ID";
    /** Database field name for ground surface type */
    public static final String GS_DATABASE_FIELD = "GS";
    /** Database field name for bridge primary key */
    public static final String BRIDGE_PK_DATABASE_FIELD = "BRIDGE_PK";
    /** Database field name for source type (ROAD or BRIDGE) */
    public static final String EMISSION_TYPE_DATABASE_FIELD = "EMISSION_TYPE";
    /** Database field name for height type (RELATIVE or ABSOLUTE) */
    public static final String HEIGHT_TYPE_DATABASE_FIELD = "HEIGHT_TYPE";

    /** Coordinate of receivers - observation points where noise levels are calculated */
    public List<Coordinate> receivers = new ArrayList<>();
    /** Primary keys of receivers for database correlation */
    public List<Long> receiversPk = new ArrayList<>();
    /** Receiver height type for each receiver - determines how Z coordinates are interpreted */
    public Map<Long, HeightType> receiverHeightType = new HashMap<>();
    /** Receiver relative height above ground level for each receiver */
    public Map<Long, Double> receiverRelativeHeight = new HashMap<>();

    /** Primary keys of sources for database correlation and unique identification */
    public List<Long> sourcesPk = new ArrayList<>();
    /** Profile builder for terrain and building height profiles between sources and receivers */
    public ProfileBuilder profileBuilder;
    /** Source Index - spatial R-tree structure for efficient source geometry queries */
    public QueryGeometryStructure sourcesIndex = new QueryRTree();
    /** Sources geometries. Can be LINESTRING (linear sources) or POINT (point sources) */
    public List<Geometry> sourceGeometries = new ArrayList<>();
    /** Source orientation for directional emission computation (yaw, pitch, roll angles) */
    public Map<Long, Orientation> sourceOrientation = new HashMap<>();
    /** Bridge properties for sources located on bridges (height, virtual source flags, etc.) */
    public Map<Long, BridgeRelationship> bridgeRelationships = new HashMap<>();
    /** Source height type for each source - determines how Z coordinates are interpreted */
    public Map<Long, HeightType> sourceHeightType = new HashMap<>();


    /** Maximum reflection order - number of reflections to consider in ray tracing */
    public int reflexionOrder = 1;

    /** Default ground attenuation coefficient when no specific ground data is available */
    public double defaultGroundAttenuation = 0;

    /**
     * Default constructor - creates a Scene with default ProfileBuilder.
     * Initializes all collections and sets default values for calculation parameters.
     */
    public Scene() {
        this.profileBuilder = new ProfileBuilder();
    }

    /**
     * Constructor with custom ProfileBuilder.
     * 
     * @param profileBuilder Custom profile builder for terrain and building analysis
     */
    public Scene(ProfileBuilder profileBuilder) {
        this.profileBuilder = profileBuilder;
    }

    /** Body barrier effect - considers receiver body shadowing */
    boolean bodyBarrier = false;

    /** Compute horizontal diffraction rays over vertical edges (true by default) */
    public boolean computeHorizontalDiffraction = true;

    /** True will compute vertical diffraction over horizontal edges */
    public boolean computeVerticalDiffraction;

    /** Maximum source distance - sources beyond this distance are ignored */
    public double maxSrcDist = DEFAULT_MAX_PROPAGATION_DISTANCE;
    /** Maximum reflection wall distance from receiver to source line */
    public double maxRefDist = DEFAULT_MAXIMUM_REF_DIST;


    /**
     * Add a source geometry to the scene with auto-generated primary key.
     * Creates a spatial index entry and assigns a unique primary key for database correlation.
     * 
     * @param geom Source geometry (Point for point sources, LineString for linear sources)
     * @return Generated unique primary key for the source
     */
    @Deprecated
    public void addSource(Geometry geom) {
        if (sourceGeometries.size() > 0) {
            throw new UnsupportedOperationException("Adding sources when some are already defined is not supported. Use addSource(Long pk, Geometry geom) instead.");
        }

        sourceGeometries.add(geom);
        sourcesPk.add(0L);
        return;
    }

    /**
     * Add a source with primary key and default relative height type.
     * 
     * @param pk Source primary key for database correlation
     * @param geom Source geometry (Point or LineString)
     */
    public void addSource(Long pk, Geometry geom) {
        addSource(pk, geom, HeightType.RELATIVE, null, null);
    }

    /**
     * Add a source with primary key and specified height type.
     * 
     * @param pk Source primary key for database correlation
     * @param geom Source geometry (Point or LineString)
     * @param heightType Height interpretation (RELATIVE or ABSOLUTE)
     */
    public void addSource(Long pk, Geometry geom, HeightType heightType) {
        addSource(pk, geom, heightType, null, null);
    }

    /**
     * Add a source with primary key, height type, and orientation.
     * 
     * @param pk Source primary key for database correlation
     * @param geom Source geometry (Point or LineString)
     * @param heightType Height interpretation (RELATIVE or ABSOLUTE)
     * @param orientation Directional orientation (yaw, pitch, roll)
     */
    public void addSource(Long pk, Geometry geom, HeightType heightType, Orientation orientation) {
        addSource(pk, geom, heightType, orientation, null);
    }

    /**
     * Add a source with full attributes including bridge properties.
     * 
     * @param pk Source primary key for database correlation
     * @param geom Source geometry (Point or LineString)
     * @param heightType Height interpretation (RELATIVE or ABSOLUTE, null defaults to RELATIVE)
     * @param orientation Directional orientation (null creates omnidirectional source)
     * @param bridgeRelationship Bridge properties (null for non-bridge sources)
     */
    public void addSource(Long pk, Geometry geom,HeightType heightType,  Orientation orientation, BridgeRelationship bridgeRelationship) {
        sourceGeometries.add(geom);
        sourcesIndex.appendGeometry(geom, sourceGeometries.size() - 1);
        sourcesPk.add(pk);

        if (heightType != null) {
            sourceHeightType.put(pk, heightType);
        } else {
            sourceHeightType.put(pk, HeightType.RELATIVE);
        }

        if (orientation != null) {
            sourceOrientation.put(pk, orientation);
        } else {
            sourceOrientation.put(pk, new Orientation(0,0,0));
        }
        
        if (bridgeRelationship != null) {
            bridgeRelationships.put(pk, bridgeRelationship);
        } else {
            bridgeRelationships.put(pk, new BridgeRelationship(BridgeRelationship.RelationType.SOURCE_NOT_RELATED_TO_BRIDGE, -1L, -1L));
        }
        return;
    }

    /**
     * Get total number of sources.
     * 
     * @return Number of source geometries
     */
    public int countSources() {
        return sourceGeometries.size();
    }

    /**
     * Get all source primary keys.
     * 
     * @return List of source primary keys
     */
    public List<Long> getSourcePks() {
        return sourcesPk;
    }

    /**
     * Get source primary key by index.
     * 
     * @param index Source index
     * @return Primary key at the specified index
     */
    public long getSourcePkById(int index) {
        return sourcesPk.get(index);
    }

    /**
     * Get all source geometries.
     * 
     * @return List of source geometries
     */
    public List<Geometry> getSourceGeometries() {
        return sourceGeometries;
    }

    /**
     * Get source geometry by index.
     * 
     * @param index Source index
     * @return Geometry at the specified index
     */
    public Geometry getSourceGeometryByIndex(int index) {
        return sourceGeometries.get(index);
    }

    /**
     * Get spatial query structure for source lookups.
     * 
     * @return R-tree spatial index
     */
    public QueryGeometryStructure getSourceQuery(){
        return sourcesIndex;
    }

    /**
     * Get all source orientations.
     * 
     * @return Map of source primary keys to orientations
     */
    public Map<Long, Orientation> getSourceOrientations() {
        return sourceOrientation;
    }

    /**
     * Get orientation for a specific source.
     * 
     * @param pk Source primary key
     * @return Orientation (yaw, pitch, roll), or default (0,0,0) if not specified
     */
    public Orientation getSourceOrientationByPk(long pk) {
        Orientation orientation = sourceOrientation.get(pk);
        if (orientation == null) {
            return new Orientation(0,0,0);
        }
        return orientation;
    }

    /**
     * Get height type for a specific source.
     * 
     * @param pk Source primary key
     * @return Height type (RELATIVE or ABSOLUTE)
     */
    public HeightType getSourceHeightTypeByPk(long pk) {
        return sourceHeightType.get(pk);
    }

    /**
     * Get bridge properties for a specific source.
     * 
     * @param pk Source primary key
     * @return Bridge properties or null if not on a bridge
     */
    public BridgeRelationship getBridgeRelationshipByPk(long pk) {
        return bridgeRelationships.get(pk);
    }

    /**
     * Get all bridge properties.
     * 
     * @return List of all bridge properties
     */
    public List<BridgeRelationship> getBridgeRelationships() {
        return new ArrayList<>(bridgeRelationships.values());
    }

    /**
     * Remove a source by primary key.
     * 
     * @param pk Primary key of the source to remove
     */
    public void removeSourceByPk(long pk) {
        int index = sourcesPk.indexOf(pk);
        if (index != -1) {
            sourcesPk.remove(index);
            sourceGeometries.remove(index);
            sourceOrientation.remove(pk);
            bridgeRelationships.remove(pk);
            sourceHeightType.remove(pk);
        }
    }

    /**
     * Clear all sources from the scene.
     */
    public void clearSources() {
        sourceGeometries.clear();
        sourceOrientation.clear();
        bridgeRelationships.clear();
        sourcesPk.clear();
        sourcesIndex = new QueryRTree();
    }

    /**
     * Add a receiver with primary key and default absolute height type.
     * 
     * @param pk Receiver primary key for database correlation
     * @param position Receiver coordinate
     */
    public void addReceiver(long pk, Coordinate position) {
        addReceiver(pk, position, HeightType.RELATIVE);
    }
    
    /**
     * Add a receiver with primary key and specified height type.
     * 
     * @param pk Receiver primary key for database correlation
     * @param position Receiver coordinate
     * @param heightType Height interpretation (RELATIVE or ABSOLUTE)
     */
    public void addReceiver(long pk, Coordinate position, HeightType heightType) {
        receivers.add(position);
        receiversPk.add(pk);
        receiverHeightType.put(pk, heightType);
        receiverRelativeHeight.put(pk, -9999.0);
    }

    /**
     * Add a receiver from database result set (not yet implemented).
     * 
     * @param pk Receiver primary key
     * @param position Receiver coordinate
     * @param rs Database result set
     */
    public void addReceiver(long pk, Coordinate position, SpatialResultSet rs) {
        throw new UnsupportedOperationException("Not implemented yet");
        // addReceiver(pk, position, HeightType.RELATIVE);
    }

    /**
     * Get total number of receivers.
     * 
     * @return Number of receivers
     */
    public int countReceivers() {
        return receivers.size();
    }

    /**
     * Get all receiver coordinates.
     * 
     * @return List of receiver coordinates
     */
    public List<Coordinate> getReceivers() {
        return receivers;
    }

    /**
     * Get all receiver primary keys.
     * 
     * @return List of receiver primary keys
     */
    public List<Long> getReceiverPks() {
        return receiversPk;
    }

    /**
     * Get receiver primary key by index.
     * 
     * @param index Receiver index
     * @return Primary key at the specified index
     */
    public long getReceiverPkByIndex(int index) {
        return receiversPk.get(index);
    }

    /**
     * Get receiver coordinate by index.
     * 
     * @param index Receiver index
     * @return Coordinate at the specified index
     */
    public Coordinate getReceiverByIndex(int index) {
        return receivers.get(index);
    }

    /**
     * Get receiver coordinate by index (alias method).
     * 
     * @param index Receiver index
     * @return Coordinate at the specified index
     */
    public Coordinate getReceiverCoordinateByIndex(int index) {
        return receivers.get(index);
    }

    /**
     * Get receiver coordinate by primary key.
     * 
     * @param pk Receiver primary key
     * @return Receiver coordinate or null if not found
     */
    public Coordinate getReceiverByPk(long pk) {
        int index = receiversPk.indexOf(pk);
        if (index != -1) {
            return receivers.get(index);
        }
        return null;
    }

    /**
     * Get height type for a specific receiver.
     * 
     * @param pk Receiver primary key
     * @return Height type (RELATIVE or ABSOLUTE)
     */
    public HeightType getReceiverHeightTypeByPk(long pk) {
        return receiverHeightType.get(pk);
    }

    /**
     * Set height type for a specific receiver.
     * 
     * @param pk Receiver primary key
     * @param heightType Height type to set
     * @return Previous height type
     */
    public HeightType setReceiverHeightTypeByPk(long pk, HeightType heightType) {
        return receiverHeightType.put(pk, heightType);
    }

    /**
     * Get relative height for a specific receiver.
     * 
     * @param pk Receiver primary key
     * @return Relative height above ground
     */
    public double getReceiverRelativeHeightByPk(long pk) {
        return receiverRelativeHeight.get(pk);
    }

    /**
     * Set relative height for a specific receiver.
     * 
     * @param pk Receiver primary key
     * @param relativeHeight Relative height to set
     */
    public void setReceiverRelativeHeightByPk(long pk, double relativeHeight) {
        receiverRelativeHeight.put(pk, relativeHeight);
    }

    /**
     * Get profile builder for terrain analysis.
     * 
     * @return Profile builder instance
     */
    public ProfileBuilder getProfileBuilder() {
        return profileBuilder;
    }

    /**
     * Get terrain and building profile with additional parameters.
     * 
     * @param sourceCoordinate Source coordinate
     * @param receiverCoordinate Receiver coordinate
     * @param defaultGroundAttenuation Default ground attenuation coefficient
     * @param stopAtObstacleOverSourceReceiver Stop profile at first obstacle
     * @param sourcePointInfo Source point information
     * @return Cut profile between source and receiver
     */
    public CutProfile requestProfile(Coordinate sourceCoordinate, Coordinate receiverCoordinate, double defaultGroundAttenuation, boolean stopAtObstacleOverSourceReceiver, SourcePointInfo sourcePointInfo) {
        profileBuilder.setDefaultGroundAttenuation(defaultGroundAttenuation);
        profileBuilder.setStopAtObstacleOverSourceReceiver(stopAtObstacleOverSourceReceiver);
        return this.profileBuilder.buildProfile(sourceCoordinate, receiverCoordinate, sourcePointInfo);
    }

    /**
     * Get maximum reflection order.
     * 
     * @return Maximum number of reflections
     */
    public int getReflexionOrder() {
        return reflexionOrder;
    }

    /**
     * Set maximum reflection order.
     * 
     * @param reflexionOrder Maximum number of reflections (typically 0-3)
     */
    public void setReflexionOrder(int reflexionOrder) {
        this.reflexionOrder = reflexionOrder;
    }

    /**
     * Enable or disable horizontal diffraction.
     * 
     * @param computeHorizontalDiffraction true to enable
     */
    public void setComputeHorizontalDiffraction(boolean computeHorizontalDiffraction) {
        this.computeHorizontalDiffraction = computeHorizontalDiffraction;
    }

    /**
     * Enable or disable vertical diffraction.
     * 
     * @param computeVerticalDiffraction true to enable
     */
    public void setComputeVerticalDiffraction(boolean computeVerticalDiffraction) {
        this.computeVerticalDiffraction = computeVerticalDiffraction;
    }

    /**
     * Check if body barrier effect is enabled.
     * 
     * @return true if enabled
     */
    public boolean isBodyBarrier() {
        return bodyBarrier;
    }

    /**
     * Enable or disable body barrier effect.
     * 
     * @param bodyBarrier true to enable
     */
    public void setBodyBarrier(boolean bodyBarrier) {
        this.bodyBarrier = bodyBarrier;
    }

    /**
     * Get default ground attenuation coefficient.
     * 
     * @return Ground attenuation coefficient
     */
    public double getDefaultGroundAttenuation() {
        return defaultGroundAttenuation;
    }

    /**
     * Set default ground attenuation coefficient.
     * 
     * @param gS Ground attenuation coefficient (0.0 to 1.0)
     */
    public void setDefaultGroundAttenuation(double gS) {
        this.defaultGroundAttenuation = gS;
    }

    /**
     * Get maximum source distance.
     * 
     * @return Maximum propagation distance in meters
     */
    public double getMaxSrcDist() {
        return maxSrcDist;
    }

    /**
     * Set maximum source distance.
     * 
     * @param maxSrcDist Maximum propagation distance in meters
     */
    public void setMaxSrcDist(double maxSrcDist) {
        this.maxSrcDist = maxSrcDist;
    }
    
    /**
     * Get maximum reflection distance.
     * 
     * @return Maximum reflection distance in meters
     */
    public double getMaxRefDist() {
        return maxRefDist;
    }

    /**
     * Set maximum reflection distance.
     * 
     * @param maxRefDist Maximum reflection distance in meters
     */
    public void setMaxRefDist(double maxRefDist) {
        this.maxRefDist = maxRefDist;
    }

    /**
     * Generate hash code for this Scene based on its configuration and data.
     * Used for caching and equality comparisons.
     * 
     * @return Hash code combining all significant scene properties
     */
    @Override
    public int hashCode() {
        return Objects.hash(
            profileBuilder,
            receivers,
            receiversPk,
            receiverHeightType,
            receiverRelativeHeight,
            sourcesPk,
            sourceGeometries,
            sourceOrientation,
            bridgeRelationships,
            sourceHeightType,
            reflexionOrder,
            defaultGroundAttenuation,
            bodyBarrier,
            computeHorizontalDiffraction,
            computeVerticalDiffraction,
            maxSrcDist,
            maxRefDist
        );
    }
}