/**
 * NoiseModelling is a library capable of producing noise maps. It can be freely used either for research and education, as well as by experts in a professional use.
 * <p>
 * NoiseModelling is distributed under GPL 3 license. You can read a copy of this License in the file LICENCE provided with this software.
 * <p>
 * Official webpage : http://noise-planet.org/noisemodelling.html
 * Contact: contact@noise-planet.org
 */

package org.noise_planet.noisemodelling.pathfinder.path;

import org.h2gis.utilities.SpatialResultSet;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Geometry;
import org.noise_planet.noisemodelling.pathfinder.SourcePointInfo;
import org.noise_planet.noisemodelling.pathfinder.profilebuilder.CutProfile;
import org.noise_planet.noisemodelling.pathfinder.profilebuilder.ProfileBuilder;
import org.noise_planet.noisemodelling.pathfinder.utils.geometry.QueryGeometryStructure;
import org.noise_planet.noisemodelling.pathfinder.utils.geometry.QueryRTree;
//import org.noise_planet.noisemodelling.pathfinder.aeffacer.GeoWithSoilType;
import org.noise_planet.noisemodelling.pathfinder.utils.geometry.Orientation;

import java.util.*;
import org.noise_planet.noisemodelling.pathfinder.utils.UniqueKeyGenerator;


/**
 * Data input for a propagation process (Sub domain generated by ReceiverGridNoiseMapLoader).
 * 
 * This class manages the spatial data structure for noise propagation calculations, including:
 * - Sound sources (points, lines, polygons) with their geometries and attributes
 * - Receivers (observation points) with their coordinates
 * - Spatial indexing for efficient geometry queries
 * - Configuration for reflection, diffraction, and propagation parameters
 * - Bridge properties and source orientations for advanced modeling
 * 
 * The Scene acts as a container for all geometric and acoustic data needed to perform
 * noise propagation calculations between sources and receivers in a 3D environment.
 *
 * @author Nicolas Fortin
 * @author Pierre Aumond
 * @author Adrien Le Bellec
 */
public class Scene {
    /** Default maximum propagation distance in meters */
    public static final double DEFAULT_MAX_PROPAGATION_DISTANCE = 1200;
    /** Default maximum reflection distance in meters */
    public static final double DEFAULT_MAXIMUM_REF_DIST = 700;
    /** Default receiver distance in meters */
    public static final double DEFAULT_RECEIVER_DIST = 1.0;
    /** Default ground absorption coefficient */
    public static final double DEFAULT_G = 0.0;
    /** Default building absorption coefficient */
    public static final double DEFAULT_G_BUILDING = 0.0;
    /** Database field name for yaw angle (rotation around vertical axis) */
    public static final String YAW_DATABASE_FIELD = "YAW";
    /** Database field name for pitch angle (rotation around horizontal axis) */
    public static final String PITCH_DATABASE_FIELD = "PITCH";
    /** Database field name for roll angle (rotation around forward axis) */
    public static final String ROLL_DATABASE_FIELD = "ROLL";
    /** Database field name for directivity identifier */
    public static final String DIRECTIVITY_DATABASE_FIELD = "DIR_ID";
    /** Database field name for ground surface type */
    public static final String GS_DATABASE_FIELD = "GS";
    /** Database field name for bridge location flag */
    public static final String IS_ON_BRIDGE_DATABASE_FIELD = "ISONBRIDGE";
    /** Database field name for virtual source flag */
    public static final String IS_VIRTUAL_SOURCE_DATABASE_FIELD = "ISVIRTUALSOURCE";
    /** Database field name for bridge primary key */
    public static final String BRIDGE_PK_DATABASE_FIELD = "BRIDGEPK";
    /** Database field name for source type (ROAD or BRIDGE) */
    public static final String SOURCE_TYPE_DATABASE_FIELD = "SOURCE_TYPE";

    /** Coordinate of receivers - observation points where noise levels are calculated */
    public List<Coordinate> receivers = new ArrayList<>();
    /** Primary keys of receivers for database correlation */
    public List<Long> receiversPk = new ArrayList<>();
    /** Primary keys of sources for database correlation and unique identification */
    public List<Long> sourcesPk = new ArrayList<>();
    /** Profile builder for terrain and building height profiles between sources and receivers */
    public ProfileBuilder profileBuilder;
    /** Source Index - spatial R-tree structure for efficient source geometry queries */
    public QueryGeometryStructure sourcesIndex = new QueryRTree();
    /** Sources geometries. Can be LINESTRING (linear sources) or POINT (point sources) */
    public List<Geometry> sourceGeometries = new ArrayList<>();

    /** Source orientation for directional emission computation (yaw, pitch, roll angles) */
    public Map<Long, Orientation> sourceOrientation = new HashMap<>();

    /** Bridge properties for sources located on bridges (height, virtual source flags, etc.) */
    public Map<Long, SourceBridgeProperty> sourceBridgeProperties = new HashMap<>();

    /** Maximum reflection order - number of reflections to consider in ray tracing */
    public int reflexionOrder = 1;

    /** Default ground attenuation coefficient when no specific ground data is available */
    public double defaultGroundAttenuation = 0;

    /**
     * Default constructor - creates a Scene with default ProfileBuilder.
     * Initializes all collections and sets default values for calculation parameters.
     */
    public Scene() {
        this.profileBuilder = new ProfileBuilder();
    }

    /**
     * Constructor with custom ProfileBuilder.
     * 
     * @param profileBuilder Custom profile builder for terrain and building analysis
     */
    public Scene(ProfileBuilder profileBuilder) {
        this.profileBuilder = profileBuilder;
    }

    /**
     * Check if body barrier effect is enabled.
     * Body barrier considers the shadowing effect of the receiver's body.
     * 
     * @return true if body barrier effect is enabled
     */
    public boolean isBodyBarrier() {
        return bodyBarrier;
    }

    /**
     * Enable or disable body barrier effect.
     * When enabled, considers the shadowing effect of the receiver's body
     * which can reduce noise levels by typically 5-10 dB depending on frequency.
     * 
     * @param bodyBarrier true to enable body barrier effect
     */
    public void setBodyBarrier(boolean bodyBarrier) {
        this.bodyBarrier = bodyBarrier;
    }

    /** Body barrier effect - considers receiver body shadowing */
    boolean bodyBarrier = false;

    /** Compute horizontal diffraction rays over vertical edges (true by default) */
    public boolean computeHorizontalDiffraction = true;

    /** True will compute vertical diffraction over horizontal edges */
    public boolean computeVerticalDiffraction;

    /** Maximum source distance - sources beyond this distance are ignored */
    public double maxSrcDist = DEFAULT_MAX_PROPAGATION_DISTANCE;
    /** Maximum reflection wall distance from receiver to source line */
    public double maxRefDist = DEFAULT_MAXIMUM_REF_DIST;


    /**
     * Add a source geometry to the scene with auto-generated primary key.
     * Creates a spatial index entry and assigns a unique primary key for database correlation.
     * 
     * @param geom Source geometry (Point for point sources, LineString for linear sources)
     * @return Generated unique primary key for the source
     */
    @Deprecated
    public long addSource(Geometry geom) {
        sourceGeometries.add(geom);
        sourcesIndex.appendGeometry(geom, sourceGeometries.size() - 1);
        // Add default primary key for consistency with getSourcePkById
        long registeredPk = UniqueKeyGenerator.generateLongKey((long)(sourceGeometries.size() - 1), sourcesPk); 
        sourcesPk.add(registeredPk);
        return registeredPk;
    }

    /**
     * Add a source geometry with specified primary key.
     * If the provided primary key conflicts with existing keys, a new unique key will be generated.
     * 
     * @param pk Desired primary key (null for auto-generation)
     * @param geom Source geometry (Point for point sources, LineString for linear sources)
     * @return Actual registered primary key (may differ from requested pk if conflict occurred)
     */
    public long addSource(Long pk, Geometry geom) {
        sourceGeometries.add(geom);
        sourcesIndex.appendGeometry(geom, sourceGeometries.size() - 1);
        long registeredPk = UniqueKeyGenerator.generateLongKey(pk == null ? 0L : pk.longValue(), sourcesPk);
        sourcesPk.add(registeredPk);
        return registeredPk;
    }

    /**
     * Add a source geometry with primary key and directional orientation.
     * Useful for directional sources like vehicle traffic with specific emission patterns.
     * 
     * @param pk Desired primary key (null for auto-generation)
     * @param geom Source geometry (Point for point sources, LineString for linear sources)
     * @param orientation Directional orientation (yaw, pitch, roll angles in degrees)
     * @return Actual registered primary key
     */
    public long addSource(Long pk, Geometry geom, Orientation orientation) {
        long returnedPk = addSource(pk, geom);
        sourceOrientation.put(returnedPk, orientation);
        return returnedPk;
    }

    /**
     * Add a source geometry with full attributes including bridge properties.
     * Complete method for adding sources with all possible metadata.
     * 
     * @param pk Desired primary key (null for auto-generation)
     * @param geom Source geometry (Point for point sources, LineString for linear sources)
     * @param orientation Directional orientation (can be null for omnidirectional sources)
     * @param sourceBridgeProperty Bridge-related properties (height, virtual source flags, etc.)
     * @return Actual registered primary key
     * @throws IllegalArgumentException if bridgePkOn >= 0 but source geometry does not intersect bridge footprint
     */
    public long addSource(Long pk, Geometry geom, Orientation orientation, SourceBridgeProperty sourceBridgeProperty) {
        // Validate bridge-source geometry intersection if bridge is specified
        if (sourceBridgeProperty != null && sourceBridgeProperty.getBridgePkOn() >= 0) {
            long bridgePk = sourceBridgeProperty.getBridgePkOn();
            
            // Retrieve bridge by primary key
            var bridge = profileBuilder.getBridgeByPk(bridgePk);
            if (bridge == null) {
                throw new IllegalArgumentException(
                    "Bridge with PK=" + bridgePk + " not found in ProfileBuilder. ");
            }
            
            // Check if source is contained within bridge footprint
            Geometry bridgeFootprint = bridge.getFootprintGeometry();
            if (bridgeFootprint == null || !bridgeFootprint.contains(geom)) {
                throw new IllegalArgumentException(
                    "Source geometry is not fully contained within bridge footprint. " +
                    "bridgePk=" + bridgePk + ", sourcePk=" + pk + ". " +
                    "Sources marked as ACTUAL_SOURCE_ON_BRIDGE must be completely within the bridge geometry.");
            }
        }
        
        long returnedPk = addSource(pk, geom);
        if (orientation != null) {
            sourceOrientation.put(returnedPk, orientation);
        }
        if (sourceBridgeProperty != null) {
            this.sourceBridgeProperties.put(returnedPk, sourceBridgeProperty);
        }
        return returnedPk;
    }

    /**
     * Set all source geometries at once and rebuild the spatial index.
     * Warning: This replaces all existing sources and resets their primary keys.
     * Use this method when loading sources from a database or external source.
     * 
     * @param sourceGeometries List of source geometries to set
     */
    public void setSources(List<Geometry> sourceGeometries) {
        int i = 0;
        for(Geometry source : sourceGeometries) {
            sourcesIndex.appendGeometry(source, i++);
        }
        this.sourceGeometries = sourceGeometries;
    }

    /**
     * Get all source primary keys in order.
     * 
     * @return List of source primary keys corresponding to source geometries
     */
    public List<Long> getSourcePks() {
        return sourcesPk;
    }

    /**
     * Get source primary key by index position.
     * 
     * @param index Index in the source geometries list
     * @return Primary key of the source at the specified index
     * @throws IndexOutOfBoundsException if index is out of bounds
     */
    public long getSourcePkById(int index) {
        return sourcesPk.get(index);
    }

    /**
     * Get the spatial query structure for efficient source lookups.
     * 
     * @return R-tree spatial index for source geometries
     */
    public QueryGeometryStructure getSourceQuery(){
        return sourcesIndex;
    }

    /**
     * Get all source geometries.
     * 
     * @return List of source geometries (Points and LineStrings)
     */
    public List<Geometry> getSourceGeometries() {
        return sourceGeometries;
    }

    /**
     * Get source geometry by index.
     * 
     * @param index Index in the source geometries list
     * @return Geometry at the specified index
     * @throws IndexOutOfBoundsException if index is out of bounds
     */
    public Geometry getSourceGeometryByIndex(int index) {
        return sourceGeometries.get(index);
    }

    /**
     * Get total number of sources in the scene.
     * 
     * @return Number of source geometries
     */
    public int getSourceCount() {
        return sourceGeometries.size();
    }

    /**
     * Get all source orientations mapped by primary key.
     * 
     * @return Map of source primary keys to their orientations
     */
    public Map<Long, Orientation> getSourceOrientations() {
        return sourceOrientation;
    }

    /**
     * Get orientation for a specific source by primary key.
     * Returns default orientation (0,0,0) if no orientation is specified.
     * 
     * @param pk Source primary key
     * @return Orientation object with yaw, pitch, roll angles, or default (0,0,0)
     */
    public Orientation getSourceOrientationByPk(long pk) {
        Orientation orientation = sourceOrientation.get(pk);
        if (orientation == null) {
            return new Orientation(0,0,0);
        }
        return orientation;
    }

    /**
     * Remove a source by its primary key.
     * Removes the source from all collections: geometries, orientations, bridge properties, etc.
     * 
     * @param pk Primary key of the source to remove
     */
    public void removeSourceByPk(long pk) {
        int index = sourcesPk.indexOf(pk);
        if (index != -1) {
            sourcesPk.remove(index);
            sourceGeometries.remove(index);
            sourceOrientation.remove(pk);
            sourceBridgeProperties.remove(pk);
        }
    }

    /**
     * Add one or more receiver points to the scene.
     * Receivers are observation points where noise levels will be calculated.
     * 
     * @param receiver Receiver coordinates (variable number of arguments)
     */
    public List<Coordinate> getReceivers() {
        return receivers;
    }

    public List<Long> getReceiverPks() {
        return receiversPk;
    }

    public long getReceiverPkByIndex(int index) {
        return receiversPk.get(index);
    }

    public Coordinate getReceiverByIndex(int index) {
        return receivers.get(index);
    }

    public Coordinate getReceiverByPk(long pk) {
        int index = receiversPk.indexOf(pk);
        if (index != -1) {
            return receivers.get(index);
        }
        return null;
    }

    public int getReceiverCount() {
        return receivers.size();
    }

    /**
     * Add one or more receiver points to the scene.
     * Receivers are observation points where noise levels will be calculated.
     * 
     * @param receiver Receiver coordinates (variable number of arguments)
     */
    public void addReceiver(Coordinate... receiver) {
        receivers.addAll(Arrays.asList(receiver));
    }

    /**
     * Add a receiver with primary key for database correlation.
     * 
     * @param pk Primary key for database correlation
     * @param position Receiver coordinate
     */
    public void addReceiver(long pk, Coordinate position) {
        receivers.add(position);
        receiversPk.add(pk);
    }

    /**
     * Add a receiver with primary key and database result set context.
     * 
     * @param pk Primary key for database correlation
     * @param position Receiver coordinate
     * @param rs Database result set (for future extensions)
     */
    public void addReceiver(long pk, Coordinate position, SpatialResultSet rs) {
        addReceiver(pk, position);
    }

    /**
     * Get the maximum reflection order.
     * 
     * @return Maximum number of reflections to consider in ray tracing
     */
    public int getReflexionOrder() {
        return reflexionOrder;
    }

    /**
     * Set the maximum reflection order for ray tracing.
     * Higher values provide more accurate results but increase computation time exponentially.
     * 
     * @param reflexionOrder Maximum number of reflections (typically 0-3)
     */
    public void setReflexionOrder(int reflexionOrder) {
        this.reflexionOrder = reflexionOrder;
    }

    /**
     * Enable or disable horizontal diffraction computation.
     * Horizontal diffraction considers sound bending around vertical edges of buildings.
     * 
     * @param computeHorizontalDiffraction true to enable horizontal diffraction
     */
    public void setComputeHorizontalDiffraction(boolean computeHorizontalDiffraction) {
        this.computeHorizontalDiffraction = computeHorizontalDiffraction;
    }

    /**
     * Enable or disable vertical diffraction computation.
     * Vertical diffraction considers sound bending over horizontal edges like building tops.
     * 
     * @param computeVerticalDiffraction true to enable vertical diffraction
     */
    public void setComputeVerticalDiffraction(boolean computeVerticalDiffraction) {
        this.computeVerticalDiffraction = computeVerticalDiffraction;
    }

    public double getDefaultGroundAttenuation() {
        return defaultGroundAttenuation;
    }

    public ProfileBuilder getProfileBuilder() {
        return profileBuilder;
    }

    public double getMaxSrcDist() {
        return maxSrcDist;
    }
    public void setMaxSrcDist(double maxSrcDist) {
        this.maxSrcDist = maxSrcDist;
    }
    
    public double getMaxRefDist() {
        return maxRefDist;
    }
    public void setMaxRefDist(double maxRefDist) {
        this.maxRefDist = maxRefDist;
    }

    /**
     * Set the default ground attenuation coefficient.
     * Used when no specific ground absorption data is available for a location.
     * 
     * @param gS Ground attenuation coefficient (0.0 to 1.0)
     */
    public void setDefaultGroundAttenuation(double gS) {
        this.defaultGroundAttenuation = gS;
    }

    /**
     * Get bridge properties for a specific source.
     * 
     * @param pk Source primary key
     * @return Bridge properties or null if source is not on a bridge
     */
    public SourceBridgeProperty getSourceBridgePropertyByPk(long pk) {
        return sourceBridgeProperties.get(pk);
    }

    /**
     * Get all bridge properties in the scene.
     * 
     * @return List of all bridge properties for sources located on bridges
     */
    public List<SourceBridgeProperty> getSourceBridgeProperties() {
        return new ArrayList<>(sourceBridgeProperties.values());
    }

    public CutProfile getProfile(Coordinate c0, Coordinate c1, SourcePointInfo sourcePointInfo) {
        return this.profileBuilder.getProfile(c0, c1, 0.0, false, sourcePointInfo);
    }

    public CutProfile getProfile(Coordinate sourceCoordinate, Coordinate receiverCoordinate, double defaultGroundAttenuation, boolean stopAtObstacleOverSourceReceiver, SourcePointInfo sourcePointInfo) {
        return this.profileBuilder.getProfile(sourceCoordinate, receiverCoordinate, defaultGroundAttenuation, stopAtObstacleOverSourceReceiver, sourcePointInfo);
    }

    /**
     * Clear all sources from the scene.
     * Removes all source geometries, orientations, bridge properties, and resets the spatial index.
     * Receivers are not affected by this operation.
     */
    public void clearSources() {
        sourceGeometries.clear();
        sourceOrientation.clear();
        sourceBridgeProperties.clear();
        sourcesPk.clear();
        sourcesIndex = new QueryRTree();
    }
}


